version: "3"
services:
  notebook:
    build: 
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./notebooks:/usr/src/app/notebooks
    ports:
      - 8888:8888
    command: jupyter notebook --ip '0.0.0.0' --port 8888 --allow-root --NotebookApp.token='xoxo'
